import { Metadata } from 'next';

import { AppProvider } from '@/context/context';
import Providers from '@/providers/Providers';
import LayoutView from '@/views/LayoutView';

import '@/public/css/line-awesome.min.css';
import '@/public/css/modal-video.scss';
import '@/styles/main.sass';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata: Metadata = {
  title: 'Lottery - Online Lotto & Lottery',
  description: 'Generated by create next app',
};

if (typeof window !== 'undefined') {
  require('bootstrap/dist/js/bootstrap.bundle.min.js');
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <AppProvider>
            <LayoutView>{children}</LayoutView>
          </AppProvider>
        </Providers>
      </body>
    </html>
  );
}
